export const FREE_SHIPPING_THRESHOLD = 1500;

export const DISTRICTS = [
  "Ancón",
  "Ate",
  "Barranco",
  "Breña",
  "Carabayllo",
  "Chaclacayo",
  "Chorrillos",
  "Cieneguilla",
  "Comas",
  "El Agustino",
  "Independencia",
  "Jesús María",
  "La Molina",
  "La Victoria",
  "Lima",
  "Lince",
  "Los Olivos",
  "Lurigancho",
  "Lurín",
  "Magdalena del Mar",
  "Miraflores",
  "Pachacámac",
  "Pucusana",
  "Pueblo Libre",
  "Puente Piedra",
  "Punta Hermosa",
  "Punta Negra",
  "Rímac",
  "San Bartolo",
  "San Borja",
  "San Isidro",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Luis",
  "San Martín de Porres",
  "San Miguel",
  "Santa Anita",
  "Santa María del Mar",
  "Santa Rosa",
  "Santiago de Surco",
  "Surquillo",
  "Villa El Salvador",
  "Villa María del Triunfo",
];

// Map districts to their delivery cost (mock logic based on previous implementation)
// In a real app, this might come from a DB or API
export const DELIVERY_COSTS: Record<string, number> = {
  Surquillo: 10,
  Miraflores: 12,
  "San Isidro": 12,
  Barranco: 15,
  "San Borja": 10,
  "La Molina": 18,
  "Santiago de Surco": 15,
  "Jesús María": 10,
  Lince: 10,
  "Magdalena del Mar": 12,
  "Pueblo Libre": 12,
  "San Miguel": 15,
  Chorrillos: 18,
  Lima: 8,
  // Default for others
  Ancón: 25,
  Ate: 20,
  Breña: 10,
  Carabayllo: 25,
  Chaclacayo: 25,
  Cieneguilla: 25,
  Comas: 20,
  "El Agustino": 15,
  Independencia: 15,
  "La Victoria": 10,
  "Los Olivos": 18,
  Lurigancho: 25,
  Lurín: 25,
  Pachacámac: 25,
  Pucusana: 30,
  "Puente Piedra": 25,
  "Punta Hermosa": 30,
  "Punta Negra": 30,
  Rímac: 12,
  "San Bartolo": 30,
  "San Juan de Lurigancho": 18,
  "San Juan de Miraflores": 18,
  "San Luis": 12,
  "San Martín de Porres": 18,
  "Santa Anita": 15,
  "Santa María del Mar": 30,
  "Santa Rosa": 30,
  "Villa El Salvador": 20,
  "Villa María del Triunfo": 20,
};
